apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: asia-south2-docker.pkg.dev/hossam-eissa-project/docker-repository/python:v1
        ports:
        - containerPort: 8181
          protocol: TCP

