apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: asia-south1-docker.pkg.dev/hossam-eissa-project/docker-repository/nodejs:latest
        env:
            - name: DBhosts
              value: "mongo-0.mongo:27017"
            - name: DBuser
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: DBpass
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password
        ports:
        - containerPort: 3000
          protocol: TCP

